/**
    A simple synth using sine oscillators, showing use of the voice allocator,
    message converter and envelopes
*/

// Write the input data to the application output
processor Output [[ main, width: 80, height: 60 ]]
{
    input stream float32 in_l [[ pinTop: 10 ]];
    input stream float32 in_r [[ pinTop: 10 + 25 ]];

    output stream float32 out_l [[ pinTop: 10, outputChannel: 0 ]];
    output stream float32 out_r [[ pinTop: 10 + 25, outputChannel: 1 ]];

    void main()
    {
        loop {
            out_l <- in_l;
            out_r <- in_r;
            advance();
        }
    }
}