// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'api/endpoint.dart';
import 'api/node.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Endpoint dco_decode_box_autoadd_endpoint(dynamic raw);

  @protected
  Endpoint dco_decode_endpoint(dynamic raw);

  @protected
  EndpointType dco_decode_endpoint_type(dynamic raw);

  @protected
  EventType dco_decode_event_type(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Endpoint> dco_decode_list_endpoint(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  Node dco_decode_node(dynamic raw);

  @protected
  StreamType dco_decode_stream_type(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  ValueType dco_decode_value_type(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  Endpoint sse_decode_box_autoadd_endpoint(SseDeserializer deserializer);

  @protected
  Endpoint sse_decode_endpoint(SseDeserializer deserializer);

  @protected
  EndpointType sse_decode_endpoint_type(SseDeserializer deserializer);

  @protected
  EventType sse_decode_event_type(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Endpoint> sse_decode_list_endpoint(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Node sse_decode_node(SseDeserializer deserializer);

  @protected
  StreamType sse_decode_stream_type(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  ValueType sse_decode_value_type(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_endpoint(Endpoint self, SseSerializer serializer);

  @protected
  void sse_encode_endpoint(Endpoint self, SseSerializer serializer);

  @protected
  void sse_encode_endpoint_type(EndpointType self, SseSerializer serializer);

  @protected
  void sse_encode_event_type(EventType self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_endpoint(List<Endpoint> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_node(Node self, SseSerializer serializer);

  @protected
  void sse_encode_stream_type(StreamType self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_value_type(ValueType self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
