/**
    A simple synth using sine oscillators, showing use of the voice allocator,
    message converter and envelopes
*/

// Determine the note frequency from the pitch (midi note)
processor Lfo [[ main ]]
{
    input value float32 waveform [[
        pinTop: 10,
        widget: "knob",
        left: 40,
        top: 40,
        min: 0.0,
        max: 1.0,
        default: 0.5
    ]];

    input value float32 rate [[
        pinTop: 10 + 25,
        widget: "fader",
        left: 80,
        top: 40,
        height: 100,
        min: 0.01,
        max: 100,
        default: 0.5
    ]];

    output value float32 out [[ pinTop: 10 ]];

    void main()
    {
        loop {
            out <- waveform - rate;
            advance();
        }
    }
}
