/**
    A simple control knob
*/

// Output the control value set by the knob
processor Knob [[ main, width: 300, height: 200 ]]
{
    input event float32 knobChange [[
        pinTop: 10 + 25,
        widget: "knob",
        left: 80,
        top: 40,
        // min: 0.0,
        // max: 1.0,
        default: 0.5
    ]];

    output value float32 out [[ pinTop: 10 ]];

    event knobChange(float32 v)
    {
        value = v;
    }

    float32 value = 0.0f;

    void main()
    {
        loop {
            out <- value;
            advance();
        }
    }
}
