/**
    A simple control knob
*/

// Output the control value set by the knob
processor Knob [[ main, width: 100, height: 100 ]]
{
    input event float32 knobChange [[
        widget: "knob",
        left: 20,
        top: 35,
        default: 0.5,
        color: "red"
    ]];

    output value float32 out [[ pinTop: 10 ]];

    event knobChange(float32 v)
    {
        value = v;
    }

    float32 value = 0.0f;

    void main()
    {
        loop {
            out <- value;
            advance();
        }
    }
}
