// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`

class Cable {
  final Connection source;
  final Connection destination;

  const Cable({
    required this.source,
    required this.destination,
  });

  @override
  int get hashCode => source.hashCode ^ destination.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Cable &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          destination == other.destination;
}

class Connection {
  final int nodeId;
  final int pinIndex;

  const Connection({
    required this.nodeId,
    required this.pinIndex,
  });

  @override
  int get hashCode => nodeId.hashCode ^ pinIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Connection &&
          runtimeType == other.runtimeType &&
          nodeId == other.nodeId &&
          pinIndex == other.pinIndex;
}
