// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'endpoint.freezed.dart';

// These types are ignored because they are not used by any `pub` functions: `InputHandle`, `InputStreamHandle`, `InputValueHandle`, `OutputHandle`, `OutputStreamHandle`, `OutputValueHandle`, `PrimitiveType`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `from`, `write_value`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EndpointHandle>>
abstract class EndpointHandle implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NodeEndpoint>>
abstract class NodeEndpoint implements RustOpaqueInterface {
  String get annotation;

  EndpointHandle get endpoint;

  set annotation(String annotation);

  set endpoint(EndpointHandle endpoint);

  EndpointKind get type;

  bool get isInput;

  void writeBool({required bool b});

  void writeFloat({required double v});

  void writeInt({required PlatformInt64 v});
}

@freezed
sealed class EndpointKind with _$EndpointKind {
  const EndpointKind._();

  const factory EndpointKind.stream(
    StreamType field0,
  ) = EndpointKind_Stream;
  const factory EndpointKind.value(
    ValueType field0,
  ) = EndpointKind_Value;
  const factory EndpointKind.event(
    EventType field0,
  ) = EndpointKind_Event;
}

enum EventType {
  float32,
  float64,
  int32,
  int64,
  void_,
  bool,
  ;
}

enum StreamType {
  float32,
  float64,
  int32,
  int64,
  ;
}

enum ValueType {
  float32,
  float64,
  int32,
  int64,
  void_,
  bool,
  ;
}
