// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `read_value`, `write_value`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `from`, `handle`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Endpoint>>
abstract class Endpoint implements RustOpaqueInterface {
  String get annotation;

  set annotation(String annotation);

  bool feedbackValue();

  EndpointKind get kind;

  String get type;

  bool isExternal();

  bool isInput();

  bool? readBool();

  double? readFloat();

  PlatformInt64? readInt();

  void writeBool({required bool b});

  void writeFloat({required double v});

  void writeInt({required PlatformInt64 v});
}

enum EndpointKind {
  stream,
  value,
  event,
  ;
}
