// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'endpoint.dart';
import 'node.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'patch.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ACTIONS`, `MIDI_OUTPUT`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `deref`, `initialize`, `initialize`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `prepare_patch`, `process_patch`

void setPatch({required Patch graph}) =>
    RustLib.instance.api.crateApiGraphSetPatch(graph: graph);

void clearPatch() => RustLib.instance.api.crateApiGraphClearPatch();

bool isConnectionSupported(
        {required Node srcNode,
        required NodeEndpoint srcEndpoint,
        required Node dstNode,
        required NodeEndpoint dstEndpoint}) =>
    RustLib.instance.api.crateApiGraphIsConnectionSupported(
        srcNode: srcNode,
        srcEndpoint: srcEndpoint,
        dstNode: dstNode,
        dstEndpoint: dstEndpoint);
