// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'cable.dart';
import 'node.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `process_node`, `sort_nodes_topologically`
// These types are ignored because they are not used by any `pub` functions: `GRAPH`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `prepare_patch`, `prepare`, `process_patch`, `process`

void setPatch({required Graph graph}) =>
    RustLib.instance.api.crateApiGraphSetPatch(graph: graph);

void clearPatch() => RustLib.instance.api.crateApiGraphClearPatch();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Graph>>
abstract class Graph implements RustOpaqueInterface {
  static Graph from({required List<Node> nodes, required List<Cable> cables}) =>
      RustLib.instance.api.crateApiGraphGraphFrom(nodes: nodes, cables: cables);

  factory Graph() => RustLib.instance.api.crateApiGraphGraphNew();
}
