// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'endpoint.dart';
import 'node.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Module>>
abstract class Module implements RustOpaqueInterface {
  Node createNode();

  List<String> get category;

  int get color;

  String get description;

  int get height;

  List<Endpoint> get inputs;

  String get name;

  List<Endpoint> get outputs;

  String get path;

  int get width;

  static Future<Module?> load({required String path}) =>
      RustLib.instance.api.crateApiModuleModuleLoad(path: path);
}
