// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_annotations`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

class Module {
  final String source;
  final String? name;
  final List<String> category;
  final String? title;
  final String? color;
  final String? menuIcon;
  final String? moduleIcon;
  final (int, int) size;

  const Module({
    required this.source,
    this.name,
    required this.category,
    this.title,
    this.color,
    this.menuIcon,
    this.moduleIcon,
    required this.size,
  });

  static Module from({required String source}) =>
      RustLib.instance.api.crateApiModuleModuleFrom(source: source);

  static Future<Module> load(
          {required String path, required List<String> category}) =>
      RustLib.instance.api
          .crateApiModuleModuleLoad(path: path, category: category);

  @override
  int get hashCode =>
      source.hashCode ^
      name.hashCode ^
      category.hashCode ^
      title.hashCode ^
      color.hashCode ^
      menuIcon.hashCode ^
      moduleIcon.hashCode ^
      size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Module &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          name == other.name &&
          category == other.category &&
          title == other.title &&
          color == other.color &&
          menuIcon == other.menuIcon &&
          moduleIcon == other.moduleIcon &&
          size == other.size;
}
