// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

class Module {
  final String source;
  final String? title;
  final String? titleColor;
  final String? icon;
  final int? iconSize;
  final String? iconColor;
  final (int, int) size;

  const Module({
    required this.source,
    this.title,
    this.titleColor,
    this.icon,
    this.iconSize,
    this.iconColor,
    required this.size,
  });

  static Module from({required String source}) =>
      RustLib.instance.api.crateApiModuleModuleFrom(source: source);

  @override
  int get hashCode =>
      source.hashCode ^
      title.hashCode ^
      titleColor.hashCode ^
      icon.hashCode ^
      iconSize.hashCode ^
      iconColor.hashCode ^
      size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Module &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          title == other.title &&
          titleColor == other.titleColor &&
          icon == other.icon &&
          iconSize == other.iconSize &&
          iconColor == other.iconColor &&
          size == other.size;
}
