// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'endpoint.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are not used by any `pub` functions: `ParameterChange`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Node>>
abstract class Node implements RustOpaqueInterface {
  int get id;

  Voices get voices;

  set id(int id);

  set voices(Voices voices);

  static Node? from({required String source, required int id}) =>
      RustLib.instance.api.crateApiNodeNodeFrom(source: source, id: id);

  List<NodeEndpoint> get inputs;

  List<NodeEndpoint> get outputs;
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Voices>>
abstract class Voices implements RustOpaqueInterface {}
