// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'endpoint.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Node>>
abstract class Node implements RustOpaqueInterface {
  int get id;

  ArcMutexPerformer get performer;

  set id(int id);

  set performer(ArcMutexPerformer performer);

  static Node? from({required List<String> source, required int id}) =>
      RustLib.instance.api.crateApiNodeNodeFrom(source: source, id: id);

  List<NodeEndpoint> get inputs;

  List<NodeEndpoint> get outputs;
}
