// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'endpoint.dart';
import 'module.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `clone_performer`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Node>>
abstract class Node implements RustOpaqueInterface {
  int get id;

  Module get module;

  (double, double) get position;

  set id(int id);

  set module(Module module);

  set position((double, double) position);

  static Node? fromModule(
          {required Module module, required (double, double) position}) =>
      RustLib.instance.api
          .crateApiNodeNodeFromModule(module: module, position: position);

  NodeEndpoint? getEndpointByAnnotation({required String annotation});

  NodeEndpoint? getInputByAnnotation({required String annotation});

  List<NodeEndpoint> getInputs();

  NodeEndpoint? getOutputByAnnotation({required String annotation});

  List<NodeEndpoint> getOutputs();

  bool hasEndpoint({required NodeEndpoint endpoint});

  void setPosition({required (double, double) position});
}
