// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'cable.dart';
import 'node.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Patch>>
abstract class Patch implements RustOpaqueInterface {
  void addCable({required Cable cable});

  void addNode({required Node node});

  List<Cable> get cables;

  List<Node> get nodes;

  set cables(List<Cable> cables);

  set nodes(List<Node> nodes);

  void clear();

  factory Patch() => RustLib.instance.api.crateApiPatchPatchNew();
}
